Fix e2e tests and uploading artifacts
Shell script was wrong, let's fix it
Fix uploading with matrix jobs we would otherwise get those:

```
Error: Failed to CreateArtifact: Received non-retryable error: Failed
request: (409) Conflict: an artifact with this name already exists on
the workflow run

```

<details><summary>Details</summary></details>

Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>