fix: Add target ns annotation to on-tag
We missed it and this was causing all soft of issues when running the
tests, like this error:

"test/gitlab_merge_request_test.go:687", "msg":"Changing Title on MergeRequest
https://gitlab.pipelinesascode.com/pac/e2e-testing/-/merge_requests/184"}
gitlab_merge_request_test.go:697: assertion failed: len(prs.Items) is not 2
--- FAIL: TestGitlabMergeRequestOnUpdateAtAndLabelChange (33.54s)

Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>