Don't use kubectl apply for tkn pac resolve
we can't use k apply but need to use k create since it's a generateName:

```
% tkn pac resolve -f .tekton/pull-request.yaml | k apply -f-
error: from opc-pull-request-: cannot use generate name with apply
```

Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>